config/routes.rb
Moreappweb::Application.routes.draw do
  resources :apps do
    collection do
      get 'ipad'
      post 'more', 'subscribe'
    end
  end
  
  namespace :admin do
    resources :apps
    resources :emails
  end

  match 'admin/login' => 'Admin::Main#login', :as => :login
  match 'admin/check_login' => 'Admin::Main#check_login', :as => :check_login
  match 'admin/logout' => 'Admin::Main#logout', :as => :logout
  match 'admin/dashboard/' => 'Admin::Main#dashboard', :as => :dashboard
  
  root :to => "apps#index"
  

end

app/models/app.rb
class App < ActiveRecord::Base
  
  validates :title,
    :presence => true
  validates :desc,
    :presence => true
  
  def has_youtube?
    !self.youtube_url.blank?
  end
  
end

app/models/email.rb
class Email < ActiveRecord::Base
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :address, 
    :presence   => true,
    :format     => { :with => email_regex}, 
    :uniqueness => true

end

app/controllers/admin/apps_controller.rb
class Admin::AppsController < ApplicationController
  
  before_filter :need_login
  
  layout "admin"

  def index
    @apps = App.paginate(
      :conditions => ["app_type = ?", (params[:app_type].nil? ? "iphone" : params[:app_type])], 
      :page => params[:page], 
      :per_page => 20, 
      :order => "position desc, id desc")
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @app = App.find(params[:id])
  end

  def new
    @app = App.new
    respond_to do |format|
      format.html
    end
  end

  def edit
    @app = App.find(params[:id])
  end

  def create
    @app = App.new(params[:app])

    respond_to do |format|
      if @app.save
        flash[:success] = 'App was successfully created.'
        format.html { redirect_to(admin_app_path(@app)) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @app = App.find(params[:id])

    respond_to do |format|
      if @app.update_attributes(params[:app])
        flash[:success] = 'App was successfully updated.'
        format.html { redirect_to(admin_app_path(@app)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @app = App.find(params[:id])
    @app.destroy
    respond_to do |format|
      flash[:success] = 'A App was deleted.'
      format.html { redirect_to(admin_apps_path) }
    end
  end
  
  private
  
  def need_login
    puts params[:controller]
    puts params[:action]
    unless session[:admin_login] == SITE_SETTINGS["admin_key"]
      flash[:error] = "Login First !"
      redirect_to login_path 
    end
  end
  
end

app/controllers/admin/emails_controller.rb
class Admin::EmailsController < ApplicationController
  
  before_filter :need_login
  
  layout "admin"

  def index
    @emails = Email.paginate(:page => params[:page], :per_page => 50, :order => "id desc")
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @email = Email.find(params[:id])
  end

  def new
    @email = Email.new
    respond_to do |format|
      format.html
    end
  end

  def edit
    @email = Email.find(params[:id])
  end

  def create
    @email = Email.new(params[:email])

    respond_to do |format|
      if @email.save
        flash[:success] = 'Email was successfully created.'
        format.html { redirect_to(admin_emails_path) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @email = Email.find(params[:id])

    respond_to do |format|
      if @email.update_attributes(params[:email])
        flash[:success] = 'Email was successfully updated.'
        format.html { redirect_to(admin_emails_path) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @email = Email.find(params[:id])
    @email.destroy
    respond_to do |format|
      flash[:success] = 'A Email was deleted.'
      format.html { redirect_to(admin_emails_path) }
    end
  end
  
  private
  
  def need_login
    unless session[:admin_login] == SITE_SETTINGS["admin_key"]
      flash[:error] = "Login First !"
      redirect_to login_path 
    end
  end
  
end

app/controllers/admin/main_controller.rb
require "tool_box"
class Admin::MainController < ApplicationController
  
  layout "admin"
  
  def login
    respond_to do |format|
      format.html
    end
  end
  
  def check_login
    succ, msg = ToolBox.check_login(params[:account], params[:password])
    respond_to do |format|
      if succ
        session[:admin_login] = "iamhere"
        format.html {redirect_to admin_apps_path}
      else
        flash[:error] = msg
        format.html {redirect_to login_path}
      end
    end
  end
  
  def logout
    session[:admin_login] = nil
    redirect_to root_path
  end
  
  def dashboard
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  
  def index
    @apps = App.find(:all, 
      :conditions => ["app_type = ?", "iphone"], 
      :order => "position desc, id desc", 
      :limit => SITE_SETTINGS["each_show"])
    @on_iphone = "on-iphone"
    @app_type = "iphone"
    respond_to do |format|
      format.html
    end
  end

  def ipad
    @apps = App.find(:all, 
      :conditions => ["app_type = ?", "ipad"], 
      :order => "position desc, id desc", 
      :limit => SITE_SETTINGS["each_show"])
    @on_ipad = "on-ipad"
    @app_type = "ipad"
    respond_to do |format|
      format.html {render "apps/index"}
    end
  end

  def show
    @app = App.find(params[:id])
    @on_iphone = "on-iphone" if @app.app_type == "iphone"
    @on_ipad   = "on-ipad"   if @app.app_type == "ipad"
    respond_to do |format|
      format.html
    end
  end
  
  def more
    @apps = App.find(:all, 
      :conditions => ["app_type = ?", params[:app_type]], 
      :offset => params[:offset], 
      :limit => SITE_SETTINGS["each_show"], 
      :order => "position desc, id desc")
    @div_id = @apps.blank? ? 0 : @apps[0].id
    @offset = params[:offset].to_i + SITE_SETTINGS["each_show"]
    @app_type = params[:app_type]
    respond_to do |format|
      format.js
    end
  end
  
  def subscribe
    @email = Email.new(:address => params[:subscribe_mail])
    respond_to do |format|
      format.js
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def seo_title
    _str = []
    _str << @page_title if @page_title
    _str << SITE_SETTINGS["site_title"]
    _str.join(' - ')
  end
  
  def logined?
    !session[:user_id].nil?
  end
  
  def js_void
    "javascript:void(0);"
  end
  
  def nbsp(n=4)
    raw "&nbsp;"*n
  end
end

app/views/admin/apps/_form.html.haml
- if @app.errors.any?
  .notification.error.png_bg
    = link_to image_tag("/images/admin/icons/cross_grey_small.png"), "#", :class => "close"
    %div
      = @app.errors.full_messages.join(', ')
- form_for(@app, :url => (@app.new_record? ? admin_apps_path : admin_app_path(@app))) do |f|
  %p
    %label App Title
    = f.text_field :title, :class => "text-input medium-input"
  %p
    %label App Description
    = f.text_area :desc, :class => "text-input textarea", :style => "height: 100px;"
  %p
    %label Youtube Url
    = f.text_field :youtube_url, :class => "text-input medium-input"
  %p
    %label App Type
    = f.select :app_type, ["iphone", "ipad"]
  %p
    %label Category
    = f.select :category, SITE_SETTINGS["categories"]
  %p
    %label Position
    = f.text_field :position
    %br
    %small
      Descending sequence by position number。
  %p
    = submit_tag("Submit", :class => "button")
    

app/views/admin/apps/edit.html.haml
%h2 Welcome
%p#page-intro
  What would you like to do?
%ul.shortcut-buttons-set
  %li
    = link_to raw("<span>#{image_tag("/images/admin/icons/paper_content_pencil_48.png")}<br>Create app</span>"), new_admin_app_path, :class => "shortcut-button"
.clear
.content-box
  .content-box-header
    %h3 Edit App
    %ul.content-box-tabs
      %li
        = link_to "All", admin_apps_path
      %li
        = link_to "View", admin_app_path(@app)
      %li
        = link_to "Edit", edit_admin_app_path(@app), :class => "default-tab"
    .clear
  .content-box-content
    .tab-content.default-tab
      = render :partial => "form", :locals => {:app => @app}

app/views/admin/apps/index.html.haml
%h2 Welcome
%p#page-intro
  What would you like to do?
%ul.shortcut-buttons-set
  %li
    = link_to raw("<span>#{image_tag("/images/admin/icons/paper_content_pencil_48.png")}<br>Create app</span>"), new_admin_app_path, :class => "shortcut-button"
.clear
.content-box
  .content-box-header
    %h3 Apps List
    %ul.content-box-tabs
      %li
        = link_to "Iphone", admin_apps_path, :class => "#{'default-tab' if params[:app_type].nil?}"
      %li
        = link_to "Ipad", admin_apps_path(:app_type => "ipad"), :class => "#{'default-tab' if params[:app_type] == 'ipad'}"
    .clear
  .content-box-content
    .tab-content.default-tab
      %table
        %thead
          %tr
            %th Pos
            %th App Title
            %th Type
            %th Category
            %th Manage
        %tfoot
          %tr
            %td{:colspan => 6}
              .pagination
                = will_paginate @apps, :param_name => "page", :previous_label => "&lt;&lt;", :next_label => "&gt;&gt;"
        %tbody
          - for app in @apps
            %tr
              %td
                = app.position
              %td
                = link_to app.title, admin_app_path(app)
              %td
                = app.app_type
              %td
                = app.category
              %td
                = link_to image_tag("/images/admin/icons/pencil.png"), edit_admin_app_path(app), :title => "Edit"
                = nbsp(2)
                = link_to image_tag("/images/admin/icons/cross.png"), admin_app_path(app), :title => "Delete", :method => "delete", :confirm => "Are you sure ?"

app/views/admin/apps/new.html.haml
%h2 Welcome
%p#page-intro
  What would you like to do?
%ul.shortcut-buttons-set
  %li
    = link_to raw("<span>#{image_tag("/images/admin/icons/paper_content_pencil_48.png")}<br>Create app</span>"), new_admin_app_path, :class => "shortcut-button"
.clear
.content-box
  .content-box-header
    %h3 Create new App
    %ul.content-box-tabs
      %li
        = link_to "All", admin_apps_path
      %li
        = link_to "New", "#", :class => "default-tab"
    .clear
  .content-box-content
    .tab-content.default-tab
      = render :partial => "form", :locals => {:app => @app}

app/views/admin/apps/show.html.haml
%h2 Welcome
%p#page-intro
  What would you like to do?
%ul.shortcut-buttons-set
  %li
    = link_to raw("<span>#{image_tag("/images/admin/icons/paper_content_pencil_48.png")}<br>Create app</span>"), new_admin_app_path, :class => "shortcut-button"
.clear
.content-box
  .content-box-header
    %h3 Edit App
    %ul.content-box-tabs
      %li
        = link_to "All", admin_apps_path
      %li
        = link_to "View", admin_app_path(@app), :class => "default-tab"
      %li
        = link_to "Edit", edit_admin_app_path(@app)
    .clear
  .content-box-content
    .tab-content.default-tab
      %h4
        App Title
      %p= @app.title
      %h4
        App Description
      %p= simple_format(@app.desc)
      - if @app.has_youtube?
        %h4
          Youtube Url:
        %p= link_to @app.youtube_url, @app.youtube_url, :target => "_blank"
      %h4
        App Type
      %p= @app.app_type
      %h4
        App Category
      %p= @app.category

app/views/admin/main/dashboard.html.haml
%h2 Welcome
%p#page-intro
  What would you like to do?
%ul.shortcut-buttons-set
  %li
    = link_to raw("<span>#{image_tag("/images/admin/icons/paper_content_pencil_48.png")}<br>Create app</span>"), new_admin_app_path, :class => "shortcut-button"
  %li
    = link_to raw("<span>#{image_tag("/images/admin/icons/paper_content_pencil_48.png")}<br>Add email</span>"), new_admin_email_path, :class => "shortcut-button"
.clear

app/views/admin/main/index.html.haml
It's Dashboard

app/views/admin/main/login.html.haml
#login-wrapper.png_bg
  #login-top
    %h1
      Admin Panel
    =link_to image_tag("admin/logo.png"), root_path
  #login-content
    - form_tag(check_login_path) do
      - unless flash[:error].nil?
        .notification.information.png_bg
          %div
            = flash[:error]
      %p
        %label Account
        = text_field_tag(:account, "", :class => "text-input")
      .clear
      %p
        %label Password
        = password_field_tag(:password, "", :class => "text-input")
      .clear
      / %p{:id => "remember-password"}
      /   = check_box_tag(:remember_me)
      /   Remember me 
      .clear
      %p
        =submit_tag("Login", :class => "button")

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :icon %><br />
    <%= f.text_field :icon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/_more_apps.html.haml
%div{:id => "div_#{@div_id}", :style => "display: none;"}
  - for app in apps
    .content-box
      .content-header
      .content-layout
        .content-boddy
          .content-boddy-box
            .icon
              = image_tag(app.icon_url||SITE_SETTINGS["default_icon_path"])
            .desc
              .app-title
                .right
                  = app.category
                = link_to truncate(app.title, :length => 24, :separator => "..."), app
                = link_to nbsp(4), app.youtube_url, :title => "go youtube", :class => "youtube", :target => "_blank" if app.has_youtube?
              .app-desc
                = simple_format(app.desc)
            .clearfix
        .content-footer
          = image_tag("free_app_btn.png")
    .content-line

app/views/apps/index.html.haml
- for app in @apps
  .content-box
    .content-header
    .content-layout
      .content-boddy
        .content-boddy-box
          .icon
            = image_tag(app.icon_url||SITE_SETTINGS["default_icon_path"])
          .desc
            .app-title
              .right
                = app.category
              = link_to truncate(app.title, :length => 24, :separator => "..."), app
              = link_to nbsp(4), app.youtube_url, :title => "go youtube", :class => "youtube", :target => "_blank" if app.has_youtube?
            .app-desc
              = simple_format(app.desc)
          .clearfix
      .content-footer
        = image_tag("free_app_btn.png")
  .content-line

app/views/apps/show.html.haml
.content-box
  .content-header
  .content-layout
    .content-boddy
      .content-boddy-box
        .icon
          =image_tag(@app.icon_url)
        .desc
          .app-title
            .right
              Lifestyle
            =@app.title
            =link_to nbsp(4), @app.youtube_url, :title => "go youtube", :class => "youtube", :target => "_blank" if @app.has_youtube?
          .app-desc
            =simple_format(@app.desc)
        .clearfix
    .content-footer
      =image_tag("free_app_btn.png")
.content-line

app/views/layouts/admin.html.haml
!!!
%html(xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en")
  %head
    %title= seo_title
    %meta{'http-equiv' => "content-type", :content => "text/html; charset=UTF-8"}
    %meta{'name' => "author", :content => "#{SITE_SETTINGS["author"]}"}
    = stylesheet_link_tag "admin/reset", "admin/style", "admin/invalid"
    = javascript_include_tag "jquery", "facebox", "jquery.wysiwyg", "rails", "admin"
    = csrf_meta_tag
    = yield :header
  - if action_name == "login"
    %body#login
      = yield
  - else
    %body
      #body-wrapper
        #sidebar
          #sidebar-wrapper
            %h1#sidebar-title
              = link_to "Admin Panel", dashboard_path
            = link_to image_tag("/images/admin/logo.png", :id => "logo"), dashboard_path
            #profile-links
              Hello
              / = link_to "open messages box", "#message", :rel => "modal", :title => "Messages Box"
              %br
              %br
              = link_to "View Site", root_path, :target =>"_blank"
              |
              = link_to "Sing Out", logout_path
            %ul#main-nav
              %li
                = link_to "Dashboard", dashboard_path, :class => "nav-top-item no-submenu #{'current' if params[:controller] == "Admin::Main" and params[:action] == "dashboard"}"
              %li
                = link_to "Apps", admin_apps_path, :class => "nav-top-item #{'current' if params[:controller] == "admin/apps"}"
                %ul
                  %li
                    =link_to "All Apps", admin_apps_path, :class => "#{'current' if params[:controller] == "admin/apps" and params[:action] == "index"}"
                  %li
                    =link_to "Create new App", new_admin_app_path, :class => "#{'current' if params[:controller] == "admin/apps" and params[:action] == "new"}"
              %li
                = link_to "Emails", admin_emails_path, :class => "nav-top-item #{'current' if params[:controller] == "admin/emails"}"
                %ul
                  %li
                    =link_to "All Subscribe Emails", admin_emails_path, :class => "#{'current' if params[:controller] == "admin/emails" and params[:action] == "index"}"
                  %li
                    =link_to "Add subscribe email", new_admin_email_path, :class => "#{'current' if params[:controller] == "admin/emails" and params[:action] == "new"}"
                
            #messages.hide
              %h3
                Messages Box
              %p
                it's only for test
        #main-content
          - unless flash[:notice].nil?
            .notification.attention.png_bg
              = link_to image_tag("/images/admin/icons/cross_grey_small.png", :title => "Close this notification", :alt => "close"), "#", :class => "close"
              %div
                = flash[:notice]
          .notification.information.png_bg.hide
            = link_to image_tag("/images/admin/icons/cross_grey_small.png", :title => "Close this notification", :alt => "close"), "#", :class => "close"
            %div
              it's a information
          - unless flash[:success].nil?
            .notification.success.png_bg
              = link_to image_tag("/images/admin/icons/cross_grey_small.png", :title => "Close this notification", :alt => "close"), "#", :class => "close"
              %div
                = flash[:success]
          .notification.error.png_bg.hide
            = link_to image_tag("/images/admin/icons/cross_grey_small.png", :title => "Close this notification", :alt => "close"), "#", :class => "close"
            %div
              it's a error
          = yield
          .clear
          #footer
            %small
              &copy 2011
              = link_to "Top", "#"

app/views/layouts/application.html.haml
!!!
%html(xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en")
  %head
    %title= seo_title
    %meta{'http-equiv' => "content-type", :content => "text/html; charset=UTF-8"}
    %meta{'name' => "keywords", :content => "#{SITE_SETTINGS["keywords"]}"}
    %meta{'name' => "description", :content => "#{SITE_SETTINGS["description"]}"}
    %meta{'name' => "author", :content => "#{SITE_SETTINGS["author"]}"}
    = stylesheet_link_tag "style"
    = javascript_include_tag "jquery", "rails", "application"
    = csrf_meta_tag
    = yield :header
  %body
    .header
      .logo
        = image_tag("logo.png")
      %ul.nav
        %li= link_to raw("<span> </span>"), apps_path, :class => "iphone #{@on_iphone}"
        %li= link_to raw("<span> </span>"), ipad_apps_path, :class => "ipad #{@on_ipad}"
    .main
      .main-header
      .main-boddy
        = yield
        #more-apps-div
      .main-footer
        - if ["index", "ipad"].include?(action_name)
          .more-app-btn
            = link_to nbsp, more_apps_path(:app_type => @app_type, :offset => SITE_SETTINGS["each_show"]), :remote => true, :method => :post, :id => "more_app_btn"
      .icons-div
        .icons
          =image_tag("icon_youtube.png")
          =image_tag("icon_vimeo.png")
          =image_tag("icon_facebook.png")
          =image_tag("icon_twitter.png")
          =image_tag("icon_feeds.png")
        .line
      .subscribe-div
        .subscribe-form
          .text
            Subscribe to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!
          - form_tag subscribe_apps_path, :remote => true do
            .input
              =text_field_tag :subscribe_mail, "enter your email address", :id => "email_input", :class => "input-field", :onblur=>"addText(this);", :onfocus=>"clearText(this);"
              =image_submit_tag("subscribe_btn.png", :class => "submit-btn")
          .notice.error.hide#subscribe_error
            please enter a valid email address
          .notice.success.hide#subscribe_success
            thanks, your address has been added

    .footer
      .copyright
        Copyright &copy; 2010 www.theAppBanana.com All rights reserved.